package com.kunalashish.royalmobilec.utils

// activity.xml file code for drawer Layout
//
//<androidx.coordinatorlayout.widget.CoordinatorLayout
//android:id="@+id/coordinatorlayout"
//android:layout_width="match_parent"
//android:layout_height="match_parent">
//
//<com.google.android.material.bottomnavigation.BottomNavigationView
//android:id="@+id/bottom_navigation"
//android:layout_width="match_parent"
//android:layout_height="wrap_content"
//android:layout_alignParentBottom="true"
//android:layout_gravity="bottom"
//app:itemBackground="@color/purple_500"
//android:background="?android:attr/windowBackground"
//android:foreground="?attr/selectableItemBackground"
//app:itemIconTint="@drawable/selector"
//app:itemTextColor="@drawable/selector"
//app:menu="@menu/buttom_item" />
//
//
//<FrameLayout
//android:id="@+id/frame"
//android:layout_width="fill_parent"
//android:layout_height="fill_parent"
//android:layout_marginBottom="56dp">
//
//<com.google.android.material.appbar.AppBarLayout
//android:layout_width="match_parent"
//android:layout_height="wrap_content"
//android:theme="@style/Theme.AppCompat.DayNight.DarkActionBar"
//android:elevation="0dp">
//
//<androidx.appcompat.widget.Toolbar
//android:id="@+id/toolbar"
//android:layout_width="match_parent"
//android:layout_height="wrap_content"
//app:title="Royal_Mobile"
//app:menu="@menu/search_icon"
//android:minHeight="?attr/actionBarSize"
//android:background="@color/primary_color"
//app:layout_scrollFlags="scroll|enterAlways"/>
//
//</com.google.android.material.appbar.AppBarLayout>
//</FrameLayout>
//
//
//
//
//</androidx.coordinatorlayout.widget.CoordinatorLayout>
//
//
//
//<com.google.android.material.navigation.NavigationView
//android:visibility="gone"
//android:id="@+id/NavigationView"
//android:layout_width="match_parent"
//android:layout_height="match_parent"
//app:headerLayout="@layout/drawer_header"
//app:menu="@menu/menu_drawer"
///>
//

